version: '3'

services: 
    app:
        build: .
        image: scrappingExam
        container_name: scrapingExam
        ports:
            - '5005:5000'
        volumes:
            - ./src:/app
